parameters:
    openFoodFactsUrl: "%env(OPEN_FOOD_FACTS_URL)%"

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $openFoodFactsUrl: "%openFoodFactsUrl%"

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
